### ISSUE TITLE
Random/Incorrect inputs when using a Nintendo controller on Windows

### ISSUE THREAD

**Issue by Ch1216** [getItemFromBlock/Create-Tweaked-Controllers#1]
step 1 - plug in nintendo switch pro controller
step 2 - all inputs gets randomly pressed

https://www.youtube.com/watch?v=1CTtz4J2grU

**Comment by getItemFromBlock** [comment]
I have already observed this issue, but this is a driver problem rather that a mod problem
The thing happening here is that the gamepad is incorrectly recognized and the inputs received are wrongly interpreted. By different programs operating at a lower level (like Steam overlay) they directly implement a custom driver, which is not really feasible here due to the fact that I am limited to GLFW as input source.

**Comment by getItemFromBlock** [comment]
Not to say that anything can be done.
I think I managed in the past to use a Nintendo pro controller over bluetooth without any problems (I don't have such device so I can't 100% confirm this

**Comment by getItemFromBlock** [comment]
Also if you have a knockoff controller there is probably a way to connect it like a generic controller, I have a controller like this one
The best to do in this case is to look at the documentation of your controller, on mine I have to hold the start button while plugging it (I can also hold the middle button for 5 seconds to connect it like a xbox controller)

**Comment by getItemFromBlock** [comment]
If the above didn't work, I think you should try the methods described here
#https://github.com/MrCrayfish/Controllable/issues/304

**Comment by Ch1216** [comment]
Too bad you cant do anything, 
I do not have a knockoff controller or any other kind of controller than my NS Pro controller, which I'm using a cable for
I tried the methods you linked to, for me DS4Windows didnt work for my Nintendo switch pro controller, but GlosSi did work, even if its a bit weird to get it working
Also I know there is nothing you can do about this, but in GlosSi/Steam you cant setup the home button or even the screenshot to be a replacement for guide, since there is _no_ guide button to map to, so to anyone, I hope people whos gonna build cool stuff with this mod dont use it

**Comment by getItemFromBlock** [comment]
For switching button mappings in-game, you can do that with the advanced input mode
https://github.com/getItemFromBlock/Create-Tweaked-Controllers/wiki/The-advanced-input-mode

**Comment by Ch1216** [comment]
I meant like a setting to switch the positions of said buttons in the controller so they match up to my irl controller
but it doesnt matter much since most people will probs refer to it as the green/a button not by direction

**Comment by getItemFromBlock** [comment]
Oh I see, yeah that could be an idea for a future thing to add, the ability to switch between the two

**Comment by getItemFromBlock** [comment]
I pushed the cosmetic part, this will appears in the next update

**Comment by getItemFromBlock** [comment]
I will close this, as there is nothing better than I can really do
I will still keep this issue as a reference for other people with the same question

**Comment by Ch1216** [comment]
ok, I do think you should either put this issue in the wiki, or controllable's issue or transcribe this [website](https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad) (or just tell people to use GlosSi or DS4 if the former doesnt work)

**Comment by getItemFromBlock** [comment]
I updated the wiki to redirect people with a Nintendo controller here

**Comment by jjmr3** [comment]
This is happening to me to but I am on a mac so it is not just windows.

**Comment by EG2603** [comment]
I am using this mod with a switch pro controller but I am not having any issues. I tried using an NSO N64 controller, NSO SNES controller and Joy-Cons after I saw this but all of them worked correctly.

**Comment by getItemFromBlock** [comment]
Are you connecting them over Bluetooth?
It might be that the problem only appear when nintendo controllers are connected via usb

**Comment by EG2603** [comment]
Yes, I connected them over bluetooth.

**Comment by getItemFromBlock** [comment]
This seems to confirm what I said before then, that the problem does not appear over Bluetooth.
Thanks for letting me know

**Comment by MarcellDavi** [comment]
Hey does someone know if this mod works also with Nintendo Switch Joycons? I connected them via bluetooth but instead of pressing all buttons randomly, they are just not recognized but I can verify that they are properly connected because they show up in steam. Do Joycons even work with this mod?

**Comment by EG2603** [comment]
I tested this and only one of the joycons got recognized and the analog stick wasn't  working correctly.
@MarcellDavi

**Comment by Biggetje2011** [comment]
I added my switch controller via bluethooth and now its not getting ANY input

**Comment by Biggetje2011** [comment]
@getItemFromBlock I wanted to tell you I fixed the issue by using reWASD, the other emulators didn't work for me

**Comment by blockninja124** [comment]
I've managed to use a nintendo pro controller over USB with this mod just fine. I am on Linux though, so perhaps it works differently to windows/mac
