### ISSUE TITLE
Its not detecting my controller im useing advanced mode and it is working but then it wont detect it

### ISSUE THREAD

**Issue by CommandJohn** [getItemFromBlock/Create-Tweaked-Controllers#10]
Ok so I'm using a joystick and I'm using advanced mode and its all connected and says its working but then I push research gamepad and it wont find my joystick I have also tried with a Xbox controller and noting is working please help

**Comment by getItemFromBlock** [comment]
Research gamepad is only for simple mode, you need to configure your controller with the dedicated config menu : https://github.com/getItemFromBlock/Create-Tweaked-Controllers/wiki/The-advanced-input-mode#using-the-advanced-mode
And for more info : https://github.com/getItemFromBlock/Create-Tweaked-Controllers/wiki/Tutorials-on-the-advanced-mode#configuring-a-joystick

**Comment by CommandJohn** [comment]
Thank you but how do i then send signals with the advanced mode

**Comment by CommandJohn** [comment]
ok now there working thank you
