### ISSUE TITLE
The game's sensitivity resets when I stop using the controller.

### ISSUE THREAD

**Issue by Antony1372** [getItemFromBlock/Create-Tweaked-Controllers#11]
I play with 60% sensitivity in the game, when I stop using the controller it automatically changes to 100%. Maybe it's a configuration that I'm overlooking. Leaving that aside, the mod is extremely useful and I appreciate you working on it

**Comment by getItemFromBlock** [comment]
Might be a duplicate of https://github.com/getItemFromBlock/Create-Tweaked-Controllers/issues/9
What version are you on, and what other mods are you using ?

**Comment by Antony1372** [comment]
![Captura de pantalla 2024-02-12 171158](https://github.com/getItemFromBlock/Create-Tweaked-Controllers/assets/146195705/4e4fd8fd-84aa-430f-abae-0a5f63dcd13d)

1.18.2

**Comment by getItemFromBlock** [comment]
Alright, there might be an issue with my system then
I will have to see if switching to the other system (the one used in 1.20) fix that issue

**Comment by getItemFromBlock** [comment]
I have made a new release that should fix this issue, the release is only for 1.18 at the moment

**Comment by Antony1372** [comment]
It's completely fixed, thanks!

**Comment by getItemFromBlock** [comment]
Perfect, I will keep this open until I roll the same update for 1.19 since the 1.19 branch use the same code as the 1.18

**Comment by getItemFromBlock** [comment]
Update for 1.19 and 1.20 is out, closing this now
