### ISSUE TITLE
Joystick on controller

### ISSUE THREAD

**Issue by Doomsday9030** [getItemFromBlock/Create-Tweaked-Controllers#13]
Im trying to use the joystick forward but the slightest movement left or right triggers the other links, is there a way to fix this?

**Comment by getItemFromBlock** [comment]
I will need more informations, do you use advanced mode, and if yes how did you setup the controls ?

**Comment by Doomsday9030** [comment]
I did not use advanced mode and i set up the control via the in game config

**Comment by getItemFromBlock** [comment]
Then configure your inputs via the advanced mod, here you can set minimum and maximum values for each axis

Check this page for setting up advanced mode:
https://github.com/getItemFromBlock/Create-Tweaked-Controllers/wiki/The-advanced-input-mode

And see this page for more infos setting up a joystick and a deadzone:
https://github.com/getItemFromBlock/Create-Tweaked-Controllers/wiki/Tutorials-on-the-advanced-mode#configuring-a-joystick

Then tell me if it solves your issue

**Comment by getItemFromBlock** [comment]
Did this solved your issue ?

**Comment by getItemFromBlock** [comment]
If I don't get any response from you, I will consider that your problem is resolved. If that is not the case let me know, but without any update from your side I will have to mark this as resolved

**Comment by getItemFromBlock** [comment]
Closing this for now, let me know if you have anything new
