### ISSUE TITLE
Incompatibility with Controllable : inputs are not cancelled when using the tweaked controller

### ISSUE THREAD

**Issue by brown-boy1** [getItemFromBlock/Create-Tweaked-Controllers#2]
Using the Controllable mod with Create-Tweaked-Controllers enables the player to move while using the tweaked link controller.

**Comment by getItemFromBlock** [comment]
For this one I think I will have to see with the Controllable dev on how to implement that, and whether or not this has to be done on my side

**Comment by getItemFromBlock** [comment]
Here is the issue I made in the Controllable mod's repository : https://github.com/MrCrayfish/Controllable/issues/445

**Comment by getItemFromBlock** [comment]
Update : I managed to integrate Controllable on my side and cancel the required events.
The drawbacks are that you cannot move or turn while using the controller, and also I made that if you press your use button (usually left trigger) it will exit the controller. This makes it that one input is unavailable unless you bind it to something else.

**Comment by getItemFromBlock** [comment]
This change will appear for the next update

**Comment by brown-boy1** [comment]
Awesome, thank you for the quick response.
