### ISSUE TITLE
[CRASH] FancyMenu Crashes on Controller Configurations

### ISSUE THREAD

**Issue by Camawama** [getItemFromBlock/Create-Tweaked-Controllers#21]
My game crashes when I open the Controller Configurations menu.

Minecraft: 1.20.1
Forge: 47.2.30
CTC: 1.2.4
FancyMenu: 3.2.3

**Comment by Camawama** [comment]
[crash-2024-05-22_19.01.21-client.txt](https://github.com/getItemFromBlock/Create-Tweaked-Controllers/files/15409880/crash-2024-05-22_19.01.21-client.txt)

**Comment by getItemFromBlock** [comment]
The mod works fine for me, or at least seems to work like it should
Make sure all the dependencies are updated
Also the crash report shows that you have a lot of other mods too, so try to reproduce the crash only with CTC and FancyMenu (and their dependencies)

**Comment by getItemFromBlock** [comment]
Do you have anything new on this ? Without any updates from your side, I will have to close this
