### ISSUE TITLE
Create: clockwork — redstone resistor keeps breaking

### ISSUE THREAD

**Issue by fartunrus** [getItemFromBlock/Create-Tweaked-Controllers#22]
i use latest versions of valkyrien skies, create, clockwork and this mod on 1.20.1 version with forge version 47.3.0. Is there any fix for this? Redstone resistor is placed on the ship above phys bearing with redstone link

**Comment by getItemFromBlock** [comment]
This is not a bug with Create Tweaked Controllers, but with Clockwork. This bug can be triggered in some specific cases without my mod, but using it makes the bug easier to trigger.
Here is the bug report on the Clockwork bug tracker: https://github.com/mrsterner/Clockwork-Issues/issues/64
