### ISSUE TITLE
tally system still active

### ISSUE THREAD

**Issue by uraido** [getItemFromBlock/Create-Tweaked-Controllers#23]
https://github.com/getItemFromBlock/Create-Tweaked-Controllers/assets/79716183/ccc4fa9f-4097-475a-938b-2573374afb18

From what I understand, the 1.2.4 update for 1.20.1 should have disabled this kind of behaviour.

MC version: 1.20.1
Mod version: 1.2.4
Forge: 47.3.0

Mods folder:
![image](https://github.com/getItemFromBlock/Create-Tweaked-Controllers/assets/79716183/ca90e913-6a3e-4082-a285-5f3d4156742d)

Log:
[latest.log](https://github.com/user-attachments/files/15892423/latest.log)

Code running on the computer (perhaps this is an issue with the create cc tweaked integration/my code. In that case, forgive me for reporting this here.):
````
local gearshift = peripheral.find("Create_SequencedGearshift")

local function awaitRotation()
    while gearshift.isRunning() do end
end

local function turn(angle, orientation)
    gearshift.rotate(angle, orientation)
    awaitRotation()
end

while true do
    if redstone.getInput("front") then
        turn(360, 1)
    elseif redstone.getInput("back") then
        turn(360, -1)
    else
        sleep(0.01)
    end
end
````

**Comment by getItemFromBlock** [comment]
I was wondering why I could not reproduce the issue, but then I realized that you don't have the correct version of Tweaked Controllers
From your mods folder, it looks like you have create tweaked controllers version 1.2.2 (not 1.2.4).
Also to accomplish what you want with the code I recommend you to check out the RotationSpeedController peripheral

**Comment by uraido** [comment]
> I was wondering why I could not reproduce the issue, but then I realized that you don't have the correct version of Tweaked Controllers From your mods folder, it looks like you have create tweaked controllers version 1.2.2 (not 1.2.4). Also to accomplish what you want with the code I recommend you to check out the RotationSpeedController peripheral

Man I'm sorry for that😭. I updated the mod on my other modpack but forgot to update it in this one, which is why I was so sure of having 1.2.4. Really sorry, closing the issue.

**Comment by getItemFromBlock** [comment]
No problem, it happens to all of us
I plan to soon have a discord for the mod so that this kind of problem can be solved faster in my opinion

**Comment by uraido** [comment]
> No problem, it happens to all of us I plan to soon have a discord for the mod so that this kind of problem can be solved faster in my opinion

Yeah I originally intended to reach out to you on the VS discord server but then I found this github, which seemed more appropriate. A discord server for this mod would be nice.
