### ISSUE TITLE
PS5 Controller not found

### ISSUE THREAD

**Issue by TheAssassin4** [getItemFromBlock/Create-Tweaked-Controllers#27]
My controller is on and connected to my pc but the game still doesen't find it

**Comment by getItemFromBlock** [comment]
Try to set it up using the advanced input mode: https://github.com/getItemFromBlock/Create-Tweaked-Controllers/wiki/The-advanced-input-mode and let me know if it helps

**Comment by TheAssassin4** [comment]
> Try to set it up using the advanced input mode: https://github.com/getItemFromBlock/Create-Tweaked-Controllers/wiki/The-advanced-input-mode and let me know if it helps

All done, thx man

**Comment by getItemFromBlock** [comment]
Perfect, good to know it worked 👍
For the reference, note that I plan to change this behavior so the mod automatically detect and setup the inputs for you, since having to read a wiki in order to do a basic setup should not be a requirement
