### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by W0rrzY** [getItemFromBlock/Create-Tweaked-Controllers#30]
When i activate the controller  the buttons and joystick doesnt move, but i can,  when you activate a controller in creat you can not move because when you pressing W you wont go forward because you pressing W on controller and on this controller its the other way around, when i press W instead of pressing W i go forward. 
Anyway sorry for my english.

**Comment by getItemFromBlock** [comment]
Enable advanced input mode to use the controller with your keyboard
https://github.com/getItemFromBlock/Create-Tweaked-Controllers/wiki/The-advanced-input-mode
