### ISSUE TITLE
fabric

### ISSUE THREAD

**Issue by beiweicxy** [getItemFromBlock/Create-Tweaked-Controllers#32]
Hello, do you plan to port it to Fabric?

**Comment by getItemFromBlock** [comment]
Please don't open issues for questions like that. Taking a closer look at the Pull Requests tab, in particular https://github.com/getItemFromBlock/Create-Tweaked-Controllers/pull/16 would have given you an answer.
Fabric port is in progress and will be done when the mod is finished to be rewritten with architectury.

If you want to talk about this kind of things, prefer asking on the mod's official discord instead: https://discord.gg/3AvrppcgG3
