### ISSUE TITLE
[Feature Request] ability to use multiple input devices at once

### ISSUE THREAD

**Issue by zackadiax24** [getItemFromBlock/Create-Tweaked-Controllers#33]
I have a set of joysticks and I wanted to use them but it will only let me use one, completely ignoring the inputs of the other one. And that made me sad :(

**Comment by getItemFromBlock** [comment]
It is a planned feature of the next big update
I am still thinkering about the exact implementation of it, but that will definitely be part of the update

**Comment by zackadiax24** [comment]
I cant wait! Keep up the excellent work! Thanks!

**Comment by jam-jar-binks** [comment]
in the meantime you can make a virtual joystick using vJoy, and bind your other joysticks, throttles, and pedals to it via smth like joystick gremlin. just be sure to have it active when you configure tweaked controllers so it picks up on it.

**Comment by getItemFromBlock** [comment]
Thanks you for your feedback! And yes using a gamepad/joystick emulator is a temporary workaround until I release the next update
