### ISSUE TITLE
my rocket wont let me press the check mark so i could go to my destination in my rocket 

### ISSUE THREAD

**Issue by yesholy** [getItemFromBlock/Create-Tweaked-Controllers#36]
so i am play all of create and we got all the stuff to make the rocket and we finally finished it about an hour ago. once everything was done we sat down with our space outfit on and was ready to go when we noticed no matter what we put into the rocket control. we have enough of the liquids we need and everything is superglued together but nothing is working. it says we need a certain amount of deltaV but we have no idea how to check if we do. we've added more of the engines and tried all of the different ones they have. we are stumped and have no idea what to do. please help.

**Comment by getItemFromBlock** [comment]
As written in the github page, this is the issue tracker for Create: Tweaked controllers.
Please open an issue here only if you have a problem with my mod.
