### ISSUE TITLE
no deadzones

### ISSUE THREAD

**Issue by AlexeTataru** [getItemFromBlock/Create-Tweaked-Controllers#5]
there are no dead zones to the controler and so it dosent alow me to control without getting a stuck input

**Comment by getItemFromBlock** [comment]
Hello, please tell me if this help : https://github.com/getItemFromBlock/Create-Tweaked-Controllers/wiki/Tutorials-on-the-advanced-mode#configuring-a-deadzone

**Comment by getItemFromBlock** [comment]
You will have to enable the advanced input mode for that however

**Comment by getItemFromBlock** [comment]
I am sorry but if I don't get any response from you I will have to close this
