### ISSUE TITLE
How do I get it to work?

### ISSUE THREAD

**Issue by OttersMeep** [getItemFromBlock/Create-Tweaked-Controllers#6]
My PS4 controller isn't detected on MacOS with the latest version of the mod.

**Comment by getItemFromBlock** [comment]
Did you tried with the advanced mode ?

**Comment by OttersMeep** [comment]
Yeah, it's spotty. I closed and relaunched MC and my controller configuration was gone and it no longer works.

**Comment by OttersMeep** [comment]
I'm using the PS4 DualShock.
It worked fine for a bit, then just stopped working/

**Comment by getItemFromBlock** [comment]
It might be something with the controller profile, I suppose you saved your profile last time ?
The mod will try to load the last saved profile, but if it fails it defaults to keyboard controls
Try remaking and saving your controller profile, and tell me if it works

**Comment by OttersMeep** [comment]
I can’t remake the profile because it doesn’t detect the controller anymore.

**Comment by getItemFromBlock** [comment]
I will also check some stuff with the mod on mac (I managed to have access to one for the week)

**Comment by OttersMeep** [comment]
Also, a gamepad controller tester app and Hardware IO tools from Xcode show the controller works

**Comment by getItemFromBlock** [comment]
If the controller is no longer detected, try with the controllable mod if it works

**Comment by OttersMeep** [comment]
Thx for checking things out on the far too overpriced side of the computer spectrum
(but the deals are great if you're a college student)

**Comment by OttersMeep** [comment]
It's not detected by controllable either. I just updated MacOS so let's see if that works.
(to the dev beta I'll rollback if not)

EDIT: The controller itself is listed, but the inputs aren't in controllable.

**Comment by getItemFromBlock** [comment]
Alright, It might be an issue outside of the mod then, but I will still do the checks on my side

**Comment by OttersMeep** [comment]
Thx, ps4 support was as unhelpful as can be (they let basically anyone be a playstation "Expert" ig)

**Comment by OttersMeep** [comment]
Figured it out. Basically, DualShock controllers require you to connect via Bluetooth, then plug into USB, then unplug, and if you don't follow that exact sequence, GLFW doesn't see it.

(only on Mac idk about windows)

**Comment by getItemFromBlock** [comment]
Interesting and good to know
At least you managed to make it work
I will still perform the tests on Mac to make sure everything works as excepted

**Comment by OttersMeep** [comment]
Figured it out! For some reason GLFW doesn't detect controllers on MacOS Sonoma UNLESS they are using the default profile. Idk what code is doing that but there you go.

**Comment by getItemFromBlock** [comment]
You mean when not using the advanced mode ?

**Comment by OttersMeep** [comment]
No, I mean just always, it's not detected on a custom profile.
