### ISSUE TITLE
Resetting Mouse Sensitivity

### ISSUE THREAD

**Issue by DomezTheDragon** [getItemFromBlock/Create-Tweaked-Controllers#9]
Resets my mouse sensitivity to default when i get off the controller (1.18.2)

**Comment by getItemFromBlock** [comment]
The mod is supposed to set the mouse sensitivity to what was set before, are you using another mod(s) that could affect the mouse cursor sensitivity ?

**Comment by getItemFromBlock** [comment]
I can't help you if you don't give more infos like what other mods are you using, or what are the reproduction steps.

**Comment by getItemFromBlock** [comment]
Until new infos from your side, I will consider this a duplicate of https://github.com/getItemFromBlock/Create-Tweaked-Controllers/issues/11

**Comment by getItemFromBlock** [comment]
Update is out for 1.19 and 1.20
